In [1]:
import pandas as pd
import json

In [2]:
with open(r"C:\Users\lab\Documents\ALDBot Data\Wafer 3f2w robot\Robot campaign JSON files\0sy0t83cahsyf000fvpk6hyczr_aldbot_campaign_output.json", 'r') as f:
    campaign_dict = json.load(f)
display(campaign_dict)

{'config': {'num_runs': 50,
  'prior_datasets_dir': 'C:\\Users\\lab\\Documents\\ALDBot Data\\Wafer 3f2w robot',
  'params': {'process_pressure': 100,
   'precursor_dose_time': 15,
   'ald_valves_delay': 10,
   'precursor_purge_time': 500,
   'H2_plasma_flow_rate': 75,
   'Ar_process_flow_rate': 50,
   'ALD_purge_flow_rate': 5,
   'ALD_prep_time': 1000,
   'ALD_purge_time': 800,
   'plasma_pressure': 50,
   'plasma_duration': 2000,
   'N2_plasma_flow_rate': 0,
   'Ar_plasma_flow_rate': 0,
   'ALD_purge_plasma_flow_rate': 0,
   'RF_power_setpoint': 275,
   'LC_preset': 53,
   'TC_preset': 33,
   'plasma_prep_time': 500,
   'plasma_purge_time': 1500,
   'Number_of_ALD_cycles': 25},
  'exploration_params': ['ALD_prep_time',
   'RF_power_setpoint',
   'plasma_duration',
   'plasma_prep_time',
   'precursor_dose_time',
   'process_pressure',
   'ALD_purge_time',
   'precursor_purge_time'],
  'pre_processor': 'ald_data_processing.process_ald',
  'optimizer': 'bayesian_optimizer.Get_New_Points_With_GP',
  'modeled_params': ['ALD_prep_time',
   'RF_power_setpoint',
   'plasma_duration',
   'plasma_prep_time',
   'precursor_dose_time',
   'process_pressure',
   'ALD_purge_time',
   'precursor_purge_time'],
  'model_output_param': 'dep_rate_fit',
  'param_limits': {'ALD_prep_time': [200, 2500],
   'RF_power_setpoint': [200, 300],
   'plasma_duration': [800, 2500],
   'plasma_prep_time': [100, 2500],
   'precursor_dose_time': [10, 100],
   'process_pressure': [30, 200],
   'ALD_purge_time': [50, 2000],
   'precursor_purge_time': [50, 2000]},
  'num_RMSE_trials': 1},
 'runs': {'ALD_prep_time': {'0': 500,
   '1': 1400,
   '2': 1700,
   '3': 500,
   '4': 1900,
   '5': 1900,
   '6': 2300,
   '7': 2400,
   '8': 900,
   '9': 400,
   '10': 2497,
   '11': 2499,
   '12': 200,
   '13': 200,
   '14': 2499,
   '15': 2499,
   '16': 200,
   '17': 200,
   '18': 200,
   '19': 2499,
   '20': 200,
   '21': 2499,
   '22': 200,
   '23': 200,
   '24': 200,
   '25': 2499,
   '26': 200,
   '27': 2499,
   '28': 2499,
   '29': 200,
   '30': 2499,
   '31': 2499,
   '32': 200,
   '33': 1496,
   '34': 2499,
   '35': 2499,
   '36': 200,
   '37': 200,
   '38': 2303,
   '39': 2499,
   '40': 200,
   '41': 409,
   '42': 2499,
   '43': 2499,
   '44': 200,
   '45': 200,
   '46': 2499,
   '47': 200,
   '48': 2499,
   '49': 2499,
   '50': 200,
   '51': 2343,
   '52': 2499,
   '53': 2499,
   '54': 2075,
   '55': 436,
   '56': 2374,
   '57': 223,
   '58': 2499,
   '59': 227},
  'ALD_purge_flow_rate': {'0': 5,
   '1': 5,
   '2': 5,
   '3': 5,
   '4': 5,
   '5': 5,
   '6': 5,
   '7': 5,
   '8': 5,
   '9': 5,
   '10': 5,
   '11': 5,
   '12': 5,
   '13': 5,
   '14': 5,
   '15': 5,
   '16': 5,
   '17': 5,
   '18': 5,
   '19': 5,
   '20': 5,
   '21': 5,
   '22': 5,
   '23': 5,
   '24': 5,
   '25': 5,
   '26': 5,
   '27': 5,
   '28': 5,
   '29': 5,
   '30': 5,
   '31': 5,
   '32': 5,
   '33': 5,
   '34': 5,
   '35': 5,
   '36': 5,
   '37': 5,
   '38': 5,
   '39': 5,
   '40': 5,
   '41': 5,
   '42': 5,
   '43': 5,
   '44': 5,
   '45': 5,
   '46': 5,
   '47': 5,
   '48': 5,
   '49': 5,
   '50': 5,
   '51': 5,
   '52': 5,
   '53': 5,
   '54': 5,
   '55': 5,
   '56': 5,
   '57': 5,
   '58': 5,
   '59': 5},
  'ALD_purge_plasma_flow_rate': {'0': 0,
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '10': 0,
   '11': 0,
   '12': 0,
   '13': 0,
   '14': 0,
   '15': 0,
   '16': 0,
   '17': 0,
   '18': 0,
   '19': 0,
   '20': 0,
   '21': 0,
   '22': 0,
   '23': 0,
   '24': 0,
   '25': 0,
   '26': 0,
   '27': 0,
   '28': 0,
   '29': 0,
   '30': 0,
   '31': 0,
   '32': 0,
   '33': 0,
   '34': 0,
   '35': 0,
   '36': 0,
   '37': 0,
   '38': 0,
   '39': 0,
   '40': 0,
   '41': 0,
   '42': 0,
   '43': 0,
   '44': 0,
   '45': 0,
   '46': 0,
   '47': 0,
   '48': 0,
   '49': 0,
   '50': 0,
   '51': 0,
   '52': 0,
   '53': 0,
   '54': 0,
   '55': 0,
   '56': 0,
   '57': 0,
   '58': 0,
   '59': 0},
  'ALD_purge_time': {'0': 600,
   '1': 600,
   '2': 1000,
   '3': 1400,
   '4': 200,
   '5': 1300,
   '6': 2000,
   '7': 300,
   '8': 2400,
   '9': 200,
   '10': 1999,
   '11': 50,
   '12': 1129,
   '13': 1999,
   '14': 942,
   '15': 50,
   '16': 1438,
   '17': 810,
   '18': 50,
   '19': 1639,
   '20': 50,
   '21': 1963,
   '22': 481,
   '23': 1999,
   '24': 1261,
   '25': 608,
   '26': 1999,
   '27': 1433,
   '28': 1000,
   '29': 1705,
   '30': 1812,
   '31': 763,
   '32': 1999,
   '33': 1447,
   '34': 1999,
   '35': 1151,
   '36': 50,
   '37': 50,
   '38': 1773,
   '39': 50,
   '40': 1999,
   '41': 1730,
   '42': 50,
   '43': 1100,
   '44': 50,
   '45': 1999,
   '46': 676,
   '47': 50,
   '48': 1712,
   '49': 50,
   '50': 588,
   '51': 80,
   '52': 50,
   '53': 216,
   '54': 292,
   '55': 1915,
   '56': 111,
   '57': 1998,
   '58': 1999,
   '59': 1990},
  'Ar_plasma_flow_rate': {'0': 0,
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '10': 0,
   '11': 0,
   '12': 0,
   '13': 0,
   '14': 0,
   '15': 0,
   '16': 0,
   '17': 0,
   '18': 0,
   '19': 0,
   '20': 0,
   '21': 0,
   '22': 0,
   '23': 0,
   '24': 0,
   '25': 0,
   '26': 0,
   '27': 0,
   '28': 0,
   '29': 0,
   '30': 0,
   '31': 0,
   '32': 0,
   '33': 0,
   '34': 0,
   '35': 0,
   '36': 0,
   '37': 0,
   '38': 0,
   '39': 0,
   '40': 0,
   '41': 0,
   '42': 0,
   '43': 0,
   '44': 0,
   '45': 0,
   '46': 0,
   '47': 0,
   '48': 0,
   '49': 0,
   '50': 0,
   '51': 0,
   '52': 0,
   '53': 0,
   '54': 0,
   '55': 0,
   '56': 0,
   '57': 0,
   '58': 0,
   '59': 0},
  'Ar_process_flow_rate': {'0': 50,
   '1': 50,
   '2': 50,
   '3': 50,
   '4': 50,
   '5': 50,
   '6': 50,
   '7': 50,
   '8': 50,
   '9': 50,
   '10': 50,
   '11': 50,
   '12': 50,
   '13': 50,
   '14': 50,
   '15': 50,
   '16': 50,
   '17': 50,
   '18': 50,
   '19': 50,
   '20': 50,
   '21': 50,
   '22': 50,
   '23': 50,
   '24': 50,
   '25': 50,
   '26': 50,
   '27': 50,
   '28': 50,
   '29': 50,
   '30': 50,
   '31': 50,
   '32': 50,
   '33': 50,
   '34': 50,
   '35': 50,
   '36': 50,
   '37': 50,
   '38': 50,
   '39': 50,
   '40': 50,
   '41': 50,
   '42': 50,
   '43': 50,
   '44': 50,
   '45': 50,
   '46': 50,
   '47': 50,
   '48': 50,
   '49': 50,
   '50': 50,
   '51': 50,
   '52': 50,
   '53': 50,
   '54': 50,
   '55': 50,
   '56': 50,
   '57': 50,
   '58': 50,
   '59': 50},
  'H2_plasma_flow_rate': {'0': 75,
   '1': 75,
   '2': 75,
   '3': 75,
   '4': 75,
   '5': 75,
   '6': 75,
   '7': 75,
   '8': 75,
   '9': 75,
   '10': 75,
   '11': 75,
   '12': 75,
   '13': 75,
   '14': 75,
   '15': 75,
   '16': 75,
   '17': 75,
   '18': 75,
   '19': 75,
   '20': 75,
   '21': 75,
   '22': 75,
   '23': 75,
   '24': 75,
   '25': 75,
   '26': 75,
   '27': 75,
   '28': 75,
   '29': 75,
   '30': 75,
   '31': 75,
   '32': 75,
   '33': 75,
   '34': 75,
   '35': 75,
   '36': 75,
   '37': 75,
   '38': 75,
   '39': 75,
   '40': 75,
   '41': 75,
   '42': 75,
   '43': 75,
   '44': 75,
   '45': 75,
   '46': 75,
   '47': 75,
   '48': 75,
   '49': 75,
   '50': 75,
   '51': 75,
   '52': 75,
   '53': 75,
   '54': 75,
   '55': 75,
   '56': 75,
   '57': 75,
   '58': 75,
   '59': 75},
  'LC_preset': {'0': 53,
   '1': 53,
   '2': 49,
   '3': 54,
   '4': 53,
   '5': 53,
   '6': 53,
   '7': 53,
   '8': 60,
   '9': 53,
   '10': 53,
   '11': 53,
   '12': 53,
   '13': 53,
   '14': 53,
   '15': 53,
   '16': 53,
   '17': 53,
   '18': 53,
   '19': 53,
   '20': 53,
   '21': 53,
   '22': 53,
   '23': 53,
   '24': 53,
   '25': 53,
   '26': 53,
   '27': 53,
   '28': 53,
   '29': 53,
   '30': 53,
   '31': 53,
   '32': 53,
   '33': 53,
   '34': 53,
   '35': 53,
   '36': 53,
   '37': 53,
   '38': 53,
   '39': 53,
   '40': 53,
   '41': 53,
   '42': 53,
   '43': 53,
   '44': 53,
   '45': 53,
   '46': 53,
   '47': 53,
   '48': 53,
   '49': 53,
   '50': 53,
   '51': 53,
   '52': 53,
   '53': 53,
   '54': 53,
   '55': 53,
   '56': 53,
   '57': 53,
   '58': 53,
   '59': 53},
  'N2_plasma_flow_rate': {'0': 0,
   '1': 0,
   '2': 0,
   '3': 0,
   '4': 0,
   '5': 0,
   '6': 0,
   '7': 0,
   '8': 0,
   '9': 0,
   '10': 0,
   '11': 0,
   '12': 0,
   '13': 0,
   '14': 0,
   '15': 0,
   '16': 0,
   '17': 0,
   '18': 0,
   '19': 0,
   '20': 0,
   '21': 0,
   '22': 0,
   '23': 0,
   '24': 0,
   '25': 0,
   '26': 0,
   '27': 0,
   '28': 0,
   '29': 0,
   '30': 0,
   '31': 0,
   '32': 0,
   '33': 0,
   '34': 0,
   '35': 0,
   '36': 0,
   '37': 0,
   '38': 0,
   '39': 0,
   '40': 0,
   '41': 0,
   '42': 0,
   '43': 0,
   '44': 0,
   '45': 0,
   '46': 0,
   '47': 0,
   '48': 0,
   '49': 0,
   '50': 0,
   '51': 0,
   '52': 0,
   '53': 0,
   '54': 0,
   '55': 0,
   '56': 0,
   '57': 0,
   '58': 0,
   '59': 0},
  'Number_of_ALD_cycles': {'0': 25,
   '1': 25,
   '2': 25,
   '3': 25,
   '4': 25,
   '5': 25,
   '6': 25,
   '7': 25,
   '8': 25,
   '9': 25,
   '10': 25,
   '11': 25,
   '12': 25,
   '13': 25,
   '14': 25,
   '15': 25,
   '16': 25,
   '17': 25,
   '18': 25,
   '19': 25,
   '20': 25,
   '21': 25,
   '22': 25,
   '23': 25,
   '24': 25,
   '25': 25,
   '26': 25,
   '27': 25,
   '28': 25,
   '29': 25,
   '30': 25,
   '31': 25,
   '32': 25,
   '33': 25,
   '34': 25,
   '35': 25,
   '36': 25,
   '37': 25,
   '38': 25,
   '39': 25,
   '40': 25,
   '41': 25,
   '42': 25,
   '43': 25,
   '44': 25,
   '45': 25,
   '46': 25,
   '47': 25,
   '48': 25,
   '49': 25,
   '50': 25,
   '51': 25,
   '52': 25,
   '53': 25,
   '54': 25,
   '55': 25,
   '56': 25,
   '57': 25,
   '58': 25,
   '59': 25},
  'RF_power_setpoint': {'0': 250,
   '1': 220,
   '2': 270,
   '3': 290,
   '4': 250,
   '5': 240,
   '6': 230,
   '7': 230,
   '8': 290,
   '9': 260,
   '10': 200,
   '11': 299,
   '12': 299,
   '13': 299,
   '14': 200,
   '15': 200,
   '16': 299,
   '17': 299,
   '18': 200,
   '19': 200,
   '20': 299,
   '21': 200,
   '22': 299,
   '23': 299,
   '24': 299,
   '25': 200,
   '26': 299,
   '27': 299,
   '28': 200,
   '29': 200,
   '30': 299,
   '31': 200,
   '32': 299,
   '33': 218,
   '34': 200,
   '35': 200,
   '36': 200,
   '37': 299,
   '38': 280,
   '39': 200,
   '40': 200,
   '41': 210,
   '42': 200,
   '43': 200,
   '44': 200,
   '45': 200,
   '46': 299,
   '47': 299,
   '48': 299,
   '49': 200,
   '50': 299,
   '51': 295,
   '52': 299,
   '53': 200,
   '54': 212,
   '55': 265,
   '56': 263,
   '57': 200,
   '58': 299,
   '59': 203},
  'Sample_name': {'0': 'Wafer_3f2w_rng_1',
   '1': 'Wafer_3f2w_rng_2',
   '2': 'Wafer_3f2w_rng_3',
   '3': 'Wafer_3f2w_rng_4',
   '4': 'Wafer_3f2w_rng_5',
   '5': 'Wafer_3f2w_rng_6',
   '6': 'Wafer_3f2w_rng_7',
   '7': 'Wafer_3f2w_rng_8',
   '8': 'Wafer_3f2w_rng_9',
   '9': 'Wafer_3f2w_rng_10',
   '10': 'Wafer_3f2w_robot_run1_preexist_57',
   '11': 'Wafer_3f2w_robot_run1_preexist_57',
   '12': 'Wafer_3f2w_robot_run1_preexist_57',
   '13': 'Wafer_3f2w_robot_run1_preexist_57',
   '14': 'Wafer_3f2w_robot_run1_preexist_57',
   '15': 'Wafer_3f2w_robot_run1_preexist_57',
   '16': 'Wafer_3f2w_robot_run1_preexist_57',
   '17': 'Wafer_3f2w_robot_run1_preexist_57',
   '18': 'Wafer_3f2w_robot_run1_preexist_57',
   '19': 'Wafer_3f2w_robot_run1_preexist_57',
   '20': 'Wafer_3f2w_robot_run1_preexist_57',
   '21': 'Wafer_3f2w_robot_run1_preexist_57',
   '22': 'Wafer_3f2w_robot_run1_preexist_57',
   '23': 'Wafer_3f2w_robot_run1_preexist_57',
   '24': 'Wafer_3f2w_robot_run1_preexist_57',
   '25': 'Wafer_3f2w_robot_run1_preexist_57',
   '26': 'Wafer_3f2w_robot_run1_preexist_57',
   '27': 'Wafer_3f2w_robot_run1_preexist_57',
   '28': 'Wafer_3f2w_robot_run1_preexist_57',
   '29': 'Wafer_3f2w_robot_run1_preexist_57',
   '30': 'Wafer_3f2w_robot_run1_preexist_57',
   '31': 'Wafer_3f2w_robot_run1_preexist_57',
   '32': 'Wafer_3f2w_robot_run1_preexist_57',
   '33': 'Wafer_3f2w_robot_run1_preexist_57',
   '34': 'Wafer_3f2w_robot_run1_preexist_57',
   '35': 'Wafer_3f2w_robot_run1_preexist_57',
   '36': 'Wafer_3f2w_robot_run1_preexist_57',
   '37': 'Wafer_3f2w_robot_run1_preexist_57',
   '38': 'Wafer_3f2w_robot_run1_preexist_57',
   '39': 'Wafer_3f2w_robot_run1_preexist_57',
   '40': 'Wafer_3f2w_robot_run1_preexist_57',
   '41': 'Wafer_3f2w_robot_run1_preexist_57',
   '42': 'Wafer_3f2w_robot_run1_preexist_57',
   '43': 'Wafer_3f2w_robot_run1_preexist_57',
   '44': 'Wafer_3f2w_robot_run1_preexist_57',
   '45': 'Wafer_3f2w_robot_run1_preexist_57',
   '46': 'Wafer_3f2w_robot_run1_preexist_57',
   '47': 'Wafer_3f2w_robot_run1_preexist_57',
   '48': 'Wafer_3f2w_robot_run1_preexist_57',
   '49': 'Wafer_3f2w_robot_run1_preexist_57',
   '50': 'Wafer_3f2w_robot_run1_preexist_57',
   '51': 'Wafer_3f2w_robot_run1_preexist_57',
   '52': 'Wafer_3f2w_robot_run1_preexist_57',
   '53': 'Wafer_3f2w_robot_run1_preexist_57',
   '54': 'Wafer_3f2w_robot_run1_preexist_57',
   '55': 'Wafer_3f2w_robot_run1_preexist_57',
   '56': 'Wafer_3f2w_robot_run1_preexist_57',
   '57': 'Wafer_3f2w_robot_run1_preexist_57',
   '58': 'Wafer_3f2w_robot_run1_preexist_57',
   '59': 'Wafer_3f2w_robot_run1_preexist_57'},
  'TC_preset': {'0': 32,
   '1': 32,
   '2': 29,
   '3': 38,
   '4': 32,
   '5': 32,
   '6': 32,
   '7': 30,
   '8': 40,
   '9': 33,
   '10': 33,
   '11': 33,
   '12': 33,
   '13': 33,
   '14': 33,
   '15': 33,
   '16': 33,
   '17': 33,
   '18': 33,
   '19': 33,
   '20': 33,
   '21': 33,
   '22': 33,
   '23': 33,
   '24': 33,
   '25': 33,
   '26': 33,
   '27': 33,
   '28': 33,
   '29': 33,
   '30': 33,
   '31': 33,
   '32': 33,
   '33': 33,
   '34': 33,
   '35': 33,
   '36': 33,
   '37': 33,
   '38': 33,
   '39': 33,
   '40': 33,
   '41': 33,
   '42': 33,
   '43': 33,
   '44': 33,
   '45': 33,
   '46': 33,
   '47': 33,
   '48': 33,
   '49': 33,
   '50': 33,
   '51': 33,
   '52': 33,
   '53': 33,
   '54': 33,
   '55': 33,
   '56': 33,
   '57': 33,
   '58': 33,
   '59': 33},
  'activation': {'0': True,
   '1': True,
   '2': True,
   '3': True,
   '4': True,
   '5': True,
   '6': True,
   '7': True,
   '8': True,
   '9': True,
   '10': True,
   '11': True,
   '12': True,
   '13': True,
   '14': True,
   '15': True,
   '16': True,
   '17': True,
   '18': True,
   '19': True,
   '20': True,
   '21': True,
   '22': True,
   '23': True,
   '24': True,
   '25': True,
   '26': True,
   '27': True,
   '28': True,
   '29': True,
   '30': True,
   '31': True,
   '32': True,
   '33': True,
   '34': True,
   '35': True,
   '36': True,
   '37': True,
   '38': True,
   '39': True,
   '40': True,
   '41': True,
   '42': True,
   '43': True,
   '44': True,
   '45': True,
   '46': True,
   '47': True,
   '48': True,
   '49': True,
   '50': True,
   '51': True,
   '52': True,
   '53': True,
   '54': True,
   '55': True,
   '56': True,
   '57': True,
   '58': True,
   '59': True},
  'ald_valves_delay': {'0': 10,
   '1': 10,
   '2': 10,
   '3': 10,
   '4': 10,
   '5': 10,
   '6': 10,
   '7': 10,
   '8': 10,
   '9': 10,
   '10': 10,
   '11': 10,
   '12': 10,
   '13': 10,
   '14': 10,
   '15': 10,
   '16': 10,
   '17': 10,
   '18': 10,
   '19': 10,
   '20': 10,
   '21': 10,
   '22': 10,
   '23': 10,
   '24': 10,
   '25': 10,
   '26': 10,
   '27': 10,
   '28': 10,
   '29': 10,
   '30': 10,
   '31': 10,
   '32': 10,
   '33': 10,
   '34': 10,
   '35': 10,
   '36': 10,
   '37': 10,
   '38': 10,
   '39': 10,
   '40': 10,
   '41': 10,
   '42': 10,
   '43': 10,
   '44': 10,
   '45': 10,
   '46': 10,
   '47': 10,
   '48': 10,
   '49': 10,
   '50': 10,
   '51': 10,
   '52': 10,
   '53': 10,
   '54': 10,
   '55': 10,
   '56': 10,
   '57': 10,
   '58': 10,
   '59': 10},
  'plasma_duration': {'0': 2100,
   '1': 2100,
   '2': 1500,
   '3': 1900,
   '4': 900,
   '5': 900,
   '6': 2200,
   '7': 900,
   '8': 2200,
   '9': 1500,
   '10': 801,
   '11': 800,
   '12': 2499,
   '13': 2499,
   '14': 800,
   '15': 800,
   '16': 2499,
   '17': 2499,
   '18': 2499,
   '19': 800,
   '20': 2499,
   '21': 800,
   '22': 2499,
   '23': 2499,
   '24': 2499,
   '25': 800,
   '26': 800,
   '27': 800,
   '28': 800,
   '29': 800,
   '30': 2499,
   '31': 800,
   '32': 2499,
   '33': 1344,
   '34': 800,
   '35': 800,
   '36': 2499,
   '37': 800,
   '38': 2458,
   '39': 800,
   '40': 2499,
   '41': 2467,
   '42': 800,
   '43': 2499,
   '44': 2499,
   '45': 800,
   '46': 2499,
   '47': 800,
   '48': 800,
   '49': 2499,
   '50': 800,
   '51': 1353,
   '52': 2499,
   '53': 1523,
   '54': 2266,
   '55': 2110,
   '56': 2349,
   '57': 2497,
   '58': 800,
   '59': 2419},
  'plasma_prep_time': {'0': 1400,
   '1': 1100,
   '2': 1100,
   '3': 1100,
   '4': 500,
   '5': 600,
   '6': 900,
   '7': 200,
   '8': 200,
   '9': 400,
   '10': 2499,
   '11': 2499,
   '12': 2499,
   '13': 1829,
   '14': 2116,
   '15': 1620,
   '16': 100,
   '17': 100,
   '18': 2499,
   '19': 1725,
   '20': 1083,
   '21': 100,
   '22': 1997,
   '23': 2499,
   '24': 1766,
   '25': 2499,
   '26': 1329,
   '27': 2499,
   '28': 100,
   '29': 100,
   '30': 2499,
   '31': 2499,
   '32': 2499,
   '33': 2476,
   '34': 1512,
   '35': 100,
   '36': 2499,
   '37': 2499,
   '38': 2493,
   '39': 2124,
   '40': 778,
   '41': 2403,
   '42': 1386,
   '43': 1847,
   '44': 100,
   '45': 2499,
   '46': 2499,
   '47': 2499,
   '48': 100,
   '49': 2499,
   '50': 100,
   '51': 249,
   '52': 100,
   '53': 100,
   '54': 2479,
   '55': 2481,
   '56': 159,
   '57': 106,
   '58': 1644,
   '59': 2495},
  'plasma_pressure': {'0': 50,
   '1': 50,
   '2': 50,
   '3': 50,
   '4': 50,
   '5': 50,
   '6': 50,
   '7': 50,
   '8': 50,
   '9': 50,
   '10': 50,
   '11': 50,
   '12': 50,
   '13': 50,
   '14': 50,
   '15': 50,
   '16': 50,
   '17': 50,
   '18': 50,
   '19': 50,
   '20': 50,
   '21': 50,
   '22': 50,
   '23': 50,
   '24': 50,
   '25': 50,
   '26': 50,
   '27': 50,
   '28': 50,
   '29': 50,
   '30': 50,
   '31': 50,
   '32': 50,
   '33': 50,
   '34': 50,
   '35': 50,
   '36': 50,
   '37': 50,
   '38': 50,
   '39': 50,
   '40': 50,
   '41': 50,
   '42': 50,
   '43': 50,
   '44': 50,
   '45': 50,
   '46': 50,
   '47': 50,
   '48': 50,
   '49': 50,
   '50': 50,
   '51': 50,
   '52': 50,
   '53': 50,
   '54': 50,
   '55': 50,
   '56': 50,
   '57': 50,
   '58': 50,
   '59': 50},
  'plasma_purge_time': {'0': 1500,
   '1': 1500,
   '2': 1500,
   '3': 1500,
   '4': 1500,
   '5': 1500,
   '6': 1500,
   '7': 1500,
   '8': 1500,
   '9': 1500,
   '10': 1500,
   '11': 1500,
   '12': 1500,
   '13': 1500,
   '14': 1500,
   '15': 1500,
   '16': 1500,
   '17': 1500,
   '18': 1500,
   '19': 1500,
   '20': 1500,
   '21': 1500,
   '22': 1500,
   '23': 1500,
   '24': 1500,
   '25': 1500,
   '26': 1500,
   '27': 1500,
   '28': 1500,
   '29': 1500,
   '30': 1500,
   '31': 1500,
   '32': 1500,
   '33': 1500,
   '34': 1500,
   '35': 1500,
   '36': 1500,
   '37': 1500,
   '38': 1500,
   '39': 1500,
   '40': 1500,
   '41': 1500,
   '42': 1500,
   '43': 1500,
   '44': 1500,
   '45': 1500,
   '46': 1500,
   '47': 1500,
   '48': 1500,
   '49': 1500,
   '50': 1500,
   '51': 1500,
   '52': 1500,
   '53': 1500,
   '54': 1500,
   '55': 1500,
   '56': 1500,
   '57': 1500,
   '58': 1500,
   '59': 1500},
  'precursor_dose_time': {'0': 10,
   '1': 45,
   '2': 65,
   '3': 25,
   '4': 75,
   '5': 15,
   '6': 70,
   '7': 50,
   '8': 20,
   '9': 75,
   '10': 99,
   '11': 99,
   '12': 10,
   '13': 10,
   '14': 99,
   '15': 99,
   '16': 99,
   '17': 99,
   '18': 10,
   '19': 99,
   '20': 10,
   '21': 99,
   '22': 99,
   '23': 10,
   '24': 10,
   '25': 10,
   '26': 99,
   '27': 99,
   '28': 10,
   '29': 99,
   '30': 10,
   '31': 10,
   '32': 10,
   '33': 86,
   '34': 99,
   '35': 99,
   '36': 10,
   '37': 99,
   '38': 34,
   '39': 99,
   '40': 10,
   '41': 58,
   '42': 99,
   '43': 99,
   '44': 10,
   '45': 10,
   '46': 99,
   '47': 10,
   '48': 44,
   '49': 99,
   '50': 99,
   '51': 87,
   '52': 58,
   '53': 10,
   '54': 34,
   '55': 56,
   '56': 77,
   '57': 92,
   '58': 10,
   '59': 81},
  'precursor_purge_time': {'0': 500,
   '1': 300,
   '2': 700,
   '3': 2500,
   '4': 100,
   '5': 2000,
   '6': 1300,
   '7': 700,
   '8': 1000,
   '9': 300,
   '10': 51,
   '11': 1999,
   '12': 1999,
   '13': 50,
   '14': 50,
   '15': 1999,
   '16': 50,
   '17': 1999,
   '18': 50,
   '19': 1999,
   '20': 1999,
   '21': 1999,
   '22': 1999,

In [6]:
runs = pd.DataFrame(campaign_dict['runs'])

In [7]:
runs

,ALD_prep_time,ALD_purge_flow_rate,ALD_purge_plasma_flow_rate,ALD_purge_time,Ar_plasma_flow_rate,Ar_process_flow_rate,H2_plasma_flow_rate,LC_preset,N2_plasma_flow_rate,Number_of_ALD_cycles,...,run_id,run_state,sample,Initial_thickness,Temperature,dep_rate_fit,dep_rate_mean,dep_rate_direct,dep_rate_deviation,fit_diff_variation
0,500,5,0,600,0,50,75,53,0,25,...,0sy0s2bgs1zhb0005vkmchjbn4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,14.729,150,0.157571,0.155652,0.15580,0.010141,6.689785
1,1400,5,0,600,0,50,75,53,0,25,...,0sy0s5wb59ykq0005yzv90e9bm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,18.584,150,0.156321,0.157391,0.15680,0.006056,4.922701
2,1700,5,0,1000,0,50,75,49,0,25,...,0sy0s9p419ymz000n568c8jak0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,22.465,150,0.147250,0.148696,0.14876,0.006118,3.545283
3,500,5,0,1400,0,50,75,54,0,25,...,0sy0sdj49sxw5000n8mdm26h5c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,26.148,150,0.150571,0.152174,0.15264,0.008825,2.810243
4,1900,5,0,200,0,50,75,53,0,25,...,0sy0shck3hsx300077fgq6965g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,29.916,150,0.194500,0.196087,0.19544,0.009664,2.428498
5,1900,5,0,1300,0,50,75,53,0,25,...,0sy0smf23nvxn0001b4r075ty8,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,34.766,150,0.150214,0.151304,0.15180,0.006118,1.144414
6,2300,5,0,2000,0,50,75,53,0,25,...,0sy0sr4t0xred000v5djpj4rrm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,38.523,150,0.163857,0.162174,0.16264,0.014433,0.735227
7,2400,5,0,300,0,50,75,53,0,25,...,0sy0swrg71wc1000nq68h9zhc4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,42.540,150,0.211357,0.208261,0.20648,0.007606,1.326736
8,900,5,0,2400,0,50,75,60,0,25,...,0sy0t0fjxnz67000e6t5t6hcmw,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,47.615,150,0.175500,0.180870,0.18316,0.012824,1.139874
9,400,5,0,200,0,50,75,53,0,25,...,0sy0t4kdchxs30004cstpz3v1g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,52.060,150,0.204857,0.210000,0.20976,0.013188,2.309807
10,2497,5,0,1999,0,50,75,53,0,25,...,0sy0t88aa5sy7000bh3nvkkkf0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,57.570,150,0.159286,0.162174,0.16372,0.007197,2.613537
11,2499,5,0,50,0,50,75,53,0,25,...,0sy0tchkgsrwx00082vmdttt08,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,61.624,150,0.159214,0.160870,0.16080,0.013159,2.071193
12,200,5,0,1129,0,50,75,53,0,25,...,0sy0tg2sr9x43000rxdr950ram,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,65.604,150,0.169750,0.170000,0.16872,0.013188,0.735733
13,200,5,0,1999,0,50,75,53,0,25,...,0sy0tks0f1zkq0008a3hhqrc4r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,70.432,150,0.155607,0.158261,0.15784,0.012735,0.497796
14,2499,5,0,942,0,50,75,53,0,25,...,0sy0tqk435rns000xvtnnb450g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,74.319,150,0.168679,0.166087,0.16372,0.009664,1.016774
15,2499,5,0,50,0,50,75,53,0,25,...,0sy0tvbezswf70008zapgfd93r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,78.379,150,0.161929,0.162609,0.16316,0.007922,0.702924
16,200,5,0,1438,0,50,75,53,0,25,...,0sy0tyhprxrkq000xmtkr616xg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,82.421,150,0.143821,0.152609,0.15600,0.014512,1.495723
17,200,5,0,810,0,50,75,53,0,25,...,0sy0v1fee9w75000s5p44aq3n8,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,86.974,150,0.205929,0.203913,0.20240,0.023909,0.342945
18,200,5,0,50,0,50,75,53,0,25,...,0sy0v45cknrsq000es4rz9kzfc,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,91.977,150,0.157500,0.158261,0.15864,0.011288,0.113996
19,2499,5,0,1639,0,50,75,53,0,25,...,0sy0v7f5dhz090003k8tmcjx2g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,95.892,150,0.170500,0.169130,0.16792,0.012481,0.233513
20,200,5,0,50,0,50,75,53,0,25,...,0sy0vbbmrssf1000522hecfszg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,100.050,150,0.159036,0.167391,0.17160,0.014209,0.106042
21,2499,5,0,1963,0,50,75,53,0,25,...,0sy0ve4p0hweb000jxtyvww058,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,104.250,150,0.149429,0.142174,0.13680,0.013499,0.214921
22,200,5,0,481,0,50,75,53,0,25,...,0sy0vhfqxhyek000g64dgdcrd4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,107.640,150,0.175964,0.185652,0.18880,0.016372,0.171400
23,200,5,0,1999,0,50,75,53,0,25,...,0sy0vmsqeds3s0001ypbdmwn8c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,112.290,150,0.163179,0.166522,0.16640,0.010471,0.520346
24,200,5,0,1261,0,50,75,53,0,25,...,0sy0vrvwexxvn000zzm9m3xkn0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,116.370,150,0.168857,0.171304,0.17120,0.012616,1.181449
25,2499,5,0,608,0,50,75,53,0,25,...,0sy0vwcn9hr9f000q34nv40b80,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,120.560,150,0.158750,0.154783,0.15160,0.012112,0.703697
26,200,5,0,1999,0,50,75,53,0,25,...,0sy0w03zfxwh500020nefebrrm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,124.300,150,0.176643,0.180000,0.18080,0.013831,0.729267
27,2499,5,0,1433,0,50,75,53,0,25,...,0sy0w3360xxah000e8h2y043h0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,128.750,150,0.167000,0.168261,0.16800,0.011288,0.265452
28,2499,5,0,1000,0,50,75,53,0,25,...,0sy0w755zxv17000gd18s2e850,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,132.160,150,0.135143,0.135652,0.13520,0.009703,0.425234
29,200,5,0,1705,0,50,75,53,0,25,...,0sy0wa4m9nyk5000at15xg35gw,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,135.510,150,0.196250,0.199130,0.19920,0.013159,0.957363
30,2499,5,0,1812,0,50,75,53,0,25,...,0sy0wcgj49t9d000ab64w0j41m,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,140.440,150,0.155964,0.163913,0.16640,0.025832,0.473644
31,2499,5,0,763,0,50,75,53,0,25,...,0sy0whc0k5tn1000q4pqktpyc8,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,144.520,150,0.147286,0.143478,0.14160,0.010471,1.088452
32,200,5,0,1999,0,50,75,53,0,25,...,0sy0wn5ae9s8500080pb43hepw,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,148.030,150,0.157893,0.170455,0.17280,0.037475,1.537265
33,1496,5,0,1447,0,50,75,53,0,25,...,0sy0ws7tsnz6n000fg5kkvj9eg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,152.300,150,0.168107,0.167391,0.16680,0.008453,2.381027
34,2499,5,0,1999,0,50,75,53,0,25,...,0sy0wx552xsx9000bg9949vty0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,156.430,150,0.157036,0.156087,0.15560,0.009203,2.240041
35,2499,5,0,1151,0,50,75,53,0,25,...,0sy0x11ad1y0d000c5pve1b8v4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,160.280,150,0.193321,0.194783,0.19640,0.016384,1.608274
36,200,5,0,50,0,50,75,53,0,25,...,0sy0x42x61sf50003cx4tn9030,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,165.160,150,0.159071,0.163913,0.16560,0.009664,0.388358
37,200,5,0,50,0,50,75,53,0,25,...,0sy0x7d4vsrgv0008ka09mse5c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,169.240,150,0.154464,0.154783,0.15360,0.012465,0.270429
38,2303,5,0,1773,0,50,75,53,0,25,...,0sy0xa1fahy2s0000a22cfrp7w,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,173.030,150,0.163786,0.168261,0.17120,0.010066,0.389663
39,2499,5,0,50,0,50,75,53,0,25,...,0sy0xetzx1sfk0003j1py113r4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,177.260,150,0.150071,0.147391,0.14600,0.008953,0.333203
40,200,5,0,1999,0,50,75,53,0,25,...,0sy0xj7tv1rrx00010k0p0p3yg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,180.860,150,0.154714,0.159565,0.16080,0.011220,0.788300
41,409,5,0,1730,0,50,75,53,0,25,...,0sy0xnmq3nwj7000ae8w9tyhv0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,184.800,150,0.162964,0.164783,0.16400,0.005801,1.012364
42,2499,5,0,50,0,50,75,53,0,25,...,0sy0xsmw75wef000dy62yy06vg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,188.830,150,0.151821,0.150435,0.14840,0.008064,0.930996
43,2499,5,0,1100,0,50,75,53,0,25,...,0sy0xwsax5w4k000wmc7g8y50c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,192.480,150,0.152786,0.158261,0.16040,0.009624,1.843495
44,200,5,0,50,0,50,75,53,0,25,...,0sy0y14kchzn90005jzak9d338,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,196.410,150,0.152964,0.154783,0.15360,0.008272,1.861805
45,200,5,0,1999,0,50,75,53,0,25,...,0sy0y3h08nsrv00050ft9qkkqc,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,200.150,150,0.171143,0.164783,0.16080,0.014102,2.404316
46,2499,5,0,676,0,50,75,53,0,25,...,0sy0y6yebhty1000tdqjyre46r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,204.090,150,0.199607,0.213043,0.21160,0.031129,0.656329
47,200,5,0,50,0,50,75,53,0,25,...,0sy0ybcqp1wf900098m8rpnf1r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,209.250,150,0.177393,0.176087,0.17280,0.010525,0.256070
48,2499,5,0,1712,0,50,75,53,0,25,...,0sy0ye0cs9zd9000z42kznj510,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,213.500,150,0.160714,0.162174,0.16000,0.006565,0.471822
49,2499,5,0,50,0,50,75,53,0,25,...,0sy0yh8nxhtyd0000tbnpsefjc,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,217.450,150,0.172929,0.181739,0.18360,0.013722,0.404568
50,200,5,0,588,0,50,75,53,0,25,...,0sy0ynezd9rt7000nsbr4v1n4g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,221.970,150,0.101000,0.151875,0.09960,0.008077,0.342622
51,2343,5,0,80,0,50,75,53,0,25,...,0sy0yqcj4xyp7000asmkm61s30,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,224.400,150,0.187000,0.196957,0.19880,0.014275,0.606029
52,2499,5,0,50,0,50,75,53,0,25,...,0sy0yt7mdxwxd0000y0j621h24,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,229.280,150,0.155357,0.165652,0.16840,0.014986,0.405023
53,2499,5,0,216,0,50,75,53,0,25,...,0sy0yxg84nrzh000kfzb3yq59w,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,233.370,150,0.143250,0.140435,0.13480,0.007506,0.279444
54,2075,5,0,292,0,50,75,53,0,25,...,0sy0z0fygxy4z0001mjzhyna28,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,236.670,150,0.148536,0.153043,0.15360,0.008041,0.267587
55,436,5,0,1915,0,50,75,53,0,25,...,0sy0z4gqddz2b000p2ht2hr1t4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,240.430,150,0.152250,0.156522,0.15720,0.008652,0.597730
56,2374,5,0,111,0,50,75,53,0,25,...,0sy0z8fb3xz3q0003cpw7k3xmm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,244.270,150,0.187393,0.189565,0.18880,0.011970,0.444972
57,223,5,0,1998,0,50,75,53,0,25,...,0sy0zbqkcnrjh000479ssf7t3c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,248.880,150,0.161143,0.161304,0.15960,0.007970,0.801544
58,2499,5,0,1999,0,50,75,53,0,25,...,0sy0zewrphtzx000nbc4nnb9rr,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,252.770,150,0.164893,0.164783,0.16200,0.007144,1.202217
59,227,5,0,1990,0,50,75,53,0,25,...,0sy0zjwhpszpb000wcwhpsmw58,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,256.730,150,0.166679,0.175217,0.17240,0.014102,0.308608

In [14]:
list(runs.to_dict('records')[0].keys())

['ALD_prep_time',
 'ALD_purge_flow_rate',
 'ALD_purge_plasma_flow_rate',
 'ALD_purge_time',
 'Ar_plasma_flow_rate',
 'Ar_process_flow_rate',
 'H2_plasma_flow_rate',
 'LC_preset',
 'N2_plasma_flow_rate',
 'Number_of_ALD_cycles',
 'RF_power_setpoint',
 'Sample_name',
 'TC_preset',
 'activation',
 'ald_valves_delay',
 'plasma_duration',
 'plasma_prep_time',
 'plasma_pressure',
 'plasma_purge_time',
 'precursor_dose_time',
 'precursor_purge_time',
 'process_pressure',
 'profile',
 'progress',
 'run_description',
 'run_id',
 'run_state',
 'sample',
 'Initial_thickness',
 'Temperature',
 'dep_rate_fit',
 'dep_rate_mean',
 'dep_rate_direct',
 'dep_rate_deviation',
 'fit_diff_variation']

In [17]:
pd.DataFrame(runs.to_dict('records'))

,ALD_prep_time,ALD_purge_flow_rate,ALD_purge_plasma_flow_rate,ALD_purge_time,Ar_plasma_flow_rate,Ar_process_flow_rate,H2_plasma_flow_rate,LC_preset,N2_plasma_flow_rate,Number_of_ALD_cycles,...,run_id,run_state,sample,Initial_thickness,Temperature,dep_rate_fit,dep_rate_mean,dep_rate_direct,dep_rate_deviation,fit_diff_variation
0,500,5,0,600,0,50,75,53,0,25,...,0sy0s2bgs1zhb0005vkmchjbn4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,14.729,150,0.157571,0.155652,0.15580,0.010141,6.689785
1,1400,5,0,600,0,50,75,53,0,25,...,0sy0s5wb59ykq0005yzv90e9bm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,18.584,150,0.156321,0.157391,0.15680,0.006056,4.922701
2,1700,5,0,1000,0,50,75,49,0,25,...,0sy0s9p419ymz000n568c8jak0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,22.465,150,0.147250,0.148696,0.14876,0.006118,3.545283
3,500,5,0,1400,0,50,75,54,0,25,...,0sy0sdj49sxw5000n8mdm26h5c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,26.148,150,0.150571,0.152174,0.15264,0.008825,2.810243
4,1900,5,0,200,0,50,75,53,0,25,...,0sy0shck3hsx300077fgq6965g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,29.916,150,0.194500,0.196087,0.19544,0.009664,2.428498
5,1900,5,0,1300,0,50,75,53,0,25,...,0sy0smf23nvxn0001b4r075ty8,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,34.766,150,0.150214,0.151304,0.15180,0.006118,1.144414
6,2300,5,0,2000,0,50,75,53,0,25,...,0sy0sr4t0xred000v5djpj4rrm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,38.523,150,0.163857,0.162174,0.16264,0.014433,0.735227
7,2400,5,0,300,0,50,75,53,0,25,...,0sy0swrg71wc1000nq68h9zhc4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,42.540,150,0.211357,0.208261,0.20648,0.007606,1.326736
8,900,5,0,2400,0,50,75,60,0,25,...,0sy0t0fjxnz67000e6t5t6hcmw,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,47.615,150,0.175500,0.180870,0.18316,0.012824,1.139874
9,400,5,0,200,0,50,75,53,0,25,...,0sy0t4kdchxs30004cstpz3v1g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,52.060,150,0.204857,0.210000,0.20976,0.013188,2.309807
10,2497,5,0,1999,0,50,75,53,0,25,...,0sy0t88aa5sy7000bh3nvkkkf0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,57.570,150,0.159286,0.162174,0.16372,0.007197,2.613537
11,2499,5,0,50,0,50,75,53,0,25,...,0sy0tchkgsrwx00082vmdttt08,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,61.624,150,0.159214,0.160870,0.16080,0.013159,2.071193
12,200,5,0,1129,0,50,75,53,0,25,...,0sy0tg2sr9x43000rxdr950ram,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,65.604,150,0.169750,0.170000,0.16872,0.013188,0.735733
13,200,5,0,1999,0,50,75,53,0,25,...,0sy0tks0f1zkq0008a3hhqrc4r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,70.432,150,0.155607,0.158261,0.15784,0.012735,0.497796
14,2499,5,0,942,0,50,75,53,0,25,...,0sy0tqk435rns000xvtnnb450g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,74.319,150,0.168679,0.166087,0.16372,0.009664,1.016774
15,2499,5,0,50,0,50,75,53,0,25,...,0sy0tvbezswf70008zapgfd93r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,78.379,150,0.161929,0.162609,0.16316,0.007922,0.702924
16,200,5,0,1438,0,50,75,53,0,25,...,0sy0tyhprxrkq000xmtkr616xg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,82.421,150,0.143821,0.152609,0.15600,0.014512,1.495723
17,200,5,0,810,0,50,75,53,0,25,...,0sy0v1fee9w75000s5p44aq3n8,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,86.974,150,0.205929,0.203913,0.20240,0.023909,0.342945
18,200,5,0,50,0,50,75,53,0,25,...,0sy0v45cknrsq000es4rz9kzfc,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,91.977,150,0.157500,0.158261,0.15864,0.011288,0.113996
19,2499,5,0,1639,0,50,75,53,0,25,...,0sy0v7f5dhz090003k8tmcjx2g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,95.892,150,0.170500,0.169130,0.16792,0.012481,0.233513
20,200,5,0,50,0,50,75,53,0,25,...,0sy0vbbmrssf1000522hecfszg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,100.050,150,0.159036,0.167391,0.17160,0.014209,0.106042
21,2499,5,0,1963,0,50,75,53,0,25,...,0sy0ve4p0hweb000jxtyvww058,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,104.250,150,0.149429,0.142174,0.13680,0.013499,0.214921
22,200,5,0,481,0,50,75,53,0,25,...,0sy0vhfqxhyek000g64dgdcrd4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,107.640,150,0.175964,0.185652,0.18880,0.016372,0.171400
23,200,5,0,1999,0,50,75,53,0,25,...,0sy0vmsqeds3s0001ypbdmwn8c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,112.290,150,0.163179,0.166522,0.16640,0.010471,0.520346
24,200,5,0,1261,0,50,75,53,0,25,...,0sy0vrvwexxvn000zzm9m3xkn0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,116.370,150,0.168857,0.171304,0.17120,0.012616,1.181449
25,2499,5,0,608,0,50,75,53,0,25,...,0sy0vwcn9hr9f000q34nv40b80,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,120.560,150,0.158750,0.154783,0.15160,0.012112,0.703697
26,200,5,0,1999,0,50,75,53,0,25,...,0sy0w03zfxwh500020nefebrrm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,124.300,150,0.176643,0.180000,0.18080,0.013831,0.729267
27,2499,5,0,1433,0,50,75,53,0,25,...,0sy0w3360xxah000e8h2y043h0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,128.750,150,0.167000,0.168261,0.16800,0.011288,0.265452
28,2499,5,0,1000,0,50,75,53,0,25,...,0sy0w755zxv17000gd18s2e850,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,132.160,150,0.135143,0.135652,0.13520,0.009703,0.425234
29,200,5,0,1705,0,50,75,53,0,25,...,0sy0wa4m9nyk5000at15xg35gw,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,135.510,150,0.196250,0.199130,0.19920,0.013159,0.957363
30,2499,5,0,1812,0,50,75,53,0,25,...,0sy0wcgj49t9d000ab64w0j41m,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,140.440,150,0.155964,0.163913,0.16640,0.025832,0.473644
31,2499,5,0,763,0,50,75,53,0,25,...,0sy0whc0k5tn1000q4pqktpyc8,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,144.520,150,0.147286,0.143478,0.14160,0.010471,1.088452
32,200,5,0,1999,0,50,75,53,0,25,...,0sy0wn5ae9s8500080pb43hepw,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,148.030,150,0.157893,0.170455,0.17280,0.037475,1.537265
33,1496,5,0,1447,0,50,75,53,0,25,...,0sy0ws7tsnz6n000fg5kkvj9eg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,152.300,150,0.168107,0.167391,0.16680,0.008453,2.381027
34,2499,5,0,1999,0,50,75,53,0,25,...,0sy0wx552xsx9000bg9949vty0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,156.430,150,0.157036,0.156087,0.15560,0.009203,2.240041
35,2499,5,0,1151,0,50,75,53,0,25,...,0sy0x11ad1y0d000c5pve1b8v4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,160.280,150,0.193321,0.194783,0.19640,0.016384,1.608274
36,200,5,0,50,0,50,75,53,0,25,...,0sy0x42x61sf50003cx4tn9030,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,165.160,150,0.159071,0.163913,0.16560,0.009664,0.388358
37,200,5,0,50,0,50,75,53,0,25,...,0sy0x7d4vsrgv0008ka09mse5c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,169.240,150,0.154464,0.154783,0.15360,0.012465,0.270429
38,2303,5,0,1773,0,50,75,53,0,25,...,0sy0xa1fahy2s0000a22cfrp7w,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,173.030,150,0.163786,0.168261,0.17120,0.010066,0.389663
39,2499,5,0,50,0,50,75,53,0,25,...,0sy0xetzx1sfk0003j1py113r4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,177.260,150,0.150071,0.147391,0.14600,0.008953,0.333203
40,200,5,0,1999,0,50,75,53,0,25,...,0sy0xj7tv1rrx00010k0p0p3yg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,180.860,150,0.154714,0.159565,0.16080,0.011220,0.788300
41,409,5,0,1730,0,50,75,53,0,25,...,0sy0xnmq3nwj7000ae8w9tyhv0,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,184.800,150,0.162964,0.164783,0.16400,0.005801,1.012364
42,2499,5,0,50,0,50,75,53,0,25,...,0sy0xsmw75wef000dy62yy06vg,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,188.830,150,0.151821,0.150435,0.14840,0.008064,0.930996
43,2499,5,0,1100,0,50,75,53,0,25,...,0sy0xwsax5w4k000wmc7g8y50c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,192.480,150,0.152786,0.158261,0.16040,0.009624,1.843495
44,200,5,0,50,0,50,75,53,0,25,...,0sy0y14kchzn90005jzak9d338,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,196.410,150,0.152964,0.154783,0.15360,0.008272,1.861805
45,200,5,0,1999,0,50,75,53,0,25,...,0sy0y3h08nsrv00050ft9qkkqc,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,200.150,150,0.171143,0.164783,0.16080,0.014102,2.404316
46,2499,5,0,676,0,50,75,53,0,25,...,0sy0y6yebhty1000tdqjyre46r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,204.090,150,0.199607,0.213043,0.21160,0.031129,0.656329
47,200,5,0,50,0,50,75,53,0,25,...,0sy0ybcqp1wf900098m8rpnf1r,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,209.250,150,0.177393,0.176087,0.17280,0.010525,0.256070
48,2499,5,0,1712,0,50,75,53,0,25,...,0sy0ye0cs9zd9000z42kznj510,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,213.500,150,0.160714,0.162174,0.16000,0.006565,0.471822
49,2499,5,0,50,0,50,75,53,0,25,...,0sy0yh8nxhtyd0000tbnpsefjc,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,217.450,150,0.172929,0.181739,0.18360,0.013722,0.404568
50,200,5,0,588,0,50,75,53,0,25,...,0sy0ynezd9rt7000nsbr4v1n4g,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,221.970,150,0.101000,0.151875,0.09960,0.008077,0.342622
51,2343,5,0,80,0,50,75,53,0,25,...,0sy0yqcj4xyp7000asmkm61s30,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,224.400,150,0.187000,0.196957,0.19880,0.014275,0.606029
52,2499,5,0,50,0,50,75,53,0,25,...,0sy0yt7mdxwxd0000y0j621h24,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,229.280,150,0.155357,0.165652,0.16840,0.014986,0.405023
53,2499,5,0,216,0,50,75,53,0,25,...,0sy0yxg84nrzh000kfzb3yq59w,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,233.370,150,0.143250,0.140435,0.13480,0.007506,0.279444
54,2075,5,0,292,0,50,75,53,0,25,...,0sy0z0fygxy4z0001mjzhyna28,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,236.670,150,0.148536,0.153043,0.15360,0.008041,0.267587
55,436,5,0,1915,0,50,75,53,0,25,...,0sy0z4gqddz2b000p2ht2hr1t4,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,240.430,150,0.152250,0.156522,0.15720,0.008652,0.597730
56,2374,5,0,111,0,50,75,53,0,25,...,0sy0z8fb3xz3q0003cpw7k3xmm,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,244.270,150,0.187393,0.189565,0.18880,0.011970,0.444972
57,223,5,0,1998,0,50,75,53,0,25,...,0sy0zbqkcnrjh000479ssf7t3c,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,248.880,150,0.161143,0.161304,0.15960,0.007970,0.801544
58,2499,5,0,1999,0,50,75,53,0,25,...,0sy0zewrphtzx000nbc4nnb9rr,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,252.770,150,0.164893,0.164783,0.16200,0.007144,1.202217
59,227,5,0,1990,0,50,75,53,0,25,...,0sy0zjwhpszpb000wcwhpsmw58,run_thread_run,0sy0rg8xn9yhx000es02cb3f2w,256.730,150,0.166679,0.175217,0.17240,0.014102,0.308608